# This is a basic workflow that is manually triggered

name: pofe

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.


jobs:
  mac-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetos: [windows, darwin]
    name: pofe for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}

      - name: Compile
        run: |
          cd cmd/pofed
          go build .
          cd ..
          cd pofecli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: pofecli ${{ matrix.targetos }}
          path: cmd/pofecli/pofecli

      - uses: actions/upload-artifact@v2
        with:
          name: pofed ${{ matrix.targetos }}
          path: cmd/pofed/pofed

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv64, amd64]

    name: pofe for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          cd cmd/pofed
          go build .
          cd ..
          cd pofecli
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: pofecli ${{ matrix.arch }}
          path: cmd/pofecli/pofecli

      - uses: actions/upload-artifact@v2
        with:
          name: pofed ${{ matrix.arch }}
          path: cmd/pofed/pofed
